version: "3.8"
services:
    test:
        build:
            dockerfile: Dockerfile.test
            context: .
        environment: 
            PORT: 3000
            STAGE: test
        volumes:
            - /app/node_modules
            - .:/app
        